---
- hosts: localhost
  gather_facts: false

  vars:
    hoge: "test message"

  tasks:
    - name: debug msg
      ansible.builtin.debug:
        msg: "hello world"

    - name: debug vars
      ansible.builtin.debug:
        var: hoge
